AWSTemplateFormatVersion: 2010-09-09
Description: Creates two VPC and a ELB with a EC2 Target Group Associated

Parameters:
    SSHKeyName:
      Description: 'Name of the ec2 key you need one to use this template'
      Type: 'AWS::EC2::KeyPair::KeyName'
      Default: 'choose-key'
    instance:
      type: 'AWS::EC2::Image::Id'

    VpcId:
      Type: AWS::EC2::VPC::Id
      Description: VpcId of your existing Virtual Private Cloud (VPC)
      ConstraintDescription: must be the VPC Id of an existing Virtual Private Cloud.
    SubnetId:
      Type: AWS::EC2::Subnet::Id
      Description: SubnetId of an existing subnet (for the primary network) in your
        Virtual Public Cloud (VPC)
      ConstraintDescription: must be an existing subnet in the selected Virtual Private
        Cloud.
    SubnetId2:
      Type: AWS::EC2::Subnet::Id
      Description: SubnetId of an existing subnet (for the primary network) in your
        Virtual Public Cloud (VPC)
      ConstraintDescription: must be an existing subnet in the selected Virtual Private
        Cloud.

Resources:

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: 'SSH and Port 80 and 22'
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: '0.0.0.0/0'

  AmazonLinuxInstance2:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: !FindInMap [AWSRegionArch2AMI, !Ref 'AWS::Region', !FindInMap [AWSInstanceType2Arch,
          !Ref 'InstanceType', Arch]]
      InstanceType: !Ref 'InstanceType'
      KeyName: !Ref KeyName
      NetworkInterfaces:
        - DeviceIndex: 0
          AssociatePublicIpAddress: true
          DeleteOnTermination: true
          SubnetId: !Ref SubnetId2
          GroupSet: !Ref SecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          apt update
          apt install python-pip -y
          cd /tmp
          apt update -y
          apt install -y httpd24
          echo "Healthy" > /var/www/html/index.html
          service httpd start
          /opt/aws/bin/cfn-signal \
            -e $? \
            --stack ${AWS::StackName} \
            --resource AmazonLinuxInstance \
            --region ${AWS::Region}

  EC2TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: 30
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 15
      HealthyThresholdCount: 5
      Matcher:
        HttpCode: '200'
      Name: EC2TargetGroup
      Port: 80
      Protocol: HTTP
      TargetGroupAttributes:
      - Key: deregistration_delay.timeout_seconds
        Value: '20'
      Targets:
      - Id:
          Ref: AmazonLinuxInstance
          Ref: AmazonLinuxInstance2
        Port: 80
      UnhealthyThresholdCount: 3
      VpcId:
        Ref: 'VpcId'
      Tags:
      - Key: Name
        Value: EC2TargetGroup
      - Key: Port
        Value: 80


  ALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn:
            Ref: EC2TargetGroup
      LoadBalancerArn:
          Ref: ApplicationLoadBalancer
      Port: 80
      Protocol: HTTP
  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Scheme: internet-facing # or internal
      Subnets:
      - Ref: SubnetId
      - Ref: SubnetId2
      SecurityGroups:
      - Ref: ELBSecurityGroup

Outputs:

    VPC:
        Description: 'Virtual Private Cloud'
        Value:
          Ref: 'VPC'
    ALBHostName:
        Description: 'Application Load Balancer Hostname'
        Value:
          !GetAtt ApplicationLoadBalancer.DNSName
    EC2Instance:
        Description: 'EC2 Instance'
        Value:
          Ref: AmazonLinuxInstance
    EC2TargetGroup:
        Description: 'EC2 Target Group'
        Value:
          Ref: EC2TargetGroup
    ApplicationLoadBalancer:
        Description: 'Application Load Balancer'
        Value:
          Ref: ApplicationLoadBalancer
